test(conformance): add workflow debug steps and temporarily disable other steps

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -27,22 +27,26 @@ jobs:
         uses: actions/setup-go@v5
         with:
           go-version: stable
-      - name: Run Unit Tests
-        run: make unit-test
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: Unit Test Results
-          path: ./out/report.xml
-          reporter: java-junit
-          fail-on-error: 'true'
-      - name: Upload Reports
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: unit-test-reports
-          path: ./out/report.xml
+      #- name: Run Unit Tests
+      #  run: make unit-test
+      #- name: Test Report
+      #  uses: dorny/test-reporter@v1
+      #  if: success() || failure()
+      #  with:
+      #    name: Unit Test Results
+      #    path: ./out/report.xml
+      #    reporter: java-junit
+      #    fail-on-error: 'true'
+      #- name: Upload Reports
+      #  if: always()
+      #  uses: actions/upload-artifact@v4
+      #  with:
+      #    name: unit-test-reports
+      #    path: ./out/report.xml
+
+      - name: debug
+        run: |
+          go env
 
       - name: Run conformance tests
         env:
@@ -54,9 +58,9 @@ jobs:
       - name: Set Up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
-      - name: Go Snapshot Release
-        uses: goreleaser/goreleaser-action@v6
-        with:
-          distribution: goreleaser
-          version: v2.3.2
-          args: release --snapshot --clean --skip=publish
+      #- name: Go Snapshot Release
+      #  uses: goreleaser/goreleaser-action@v6
+      #  with:
+      #    distribution: goreleaser
+      #    version: v2.3.2
+      #    args: release --snapshot --clean --skip=publish
